### PR TITLE
remove dec show--->Add uc show

### PR DESCRIPTION
**Pull request by jaison2000b**
also added 3 below Jan show but kept it hidden till ticket links are up

### CODE REVIEW

**Comment by jaison2000b** [comment]
when I ran the code to do a sample I found a bug in the facebook link html fixing that atm

**Comment by jaison2000b** [comment]
ok also going to make the text about SJ bigger

**Comment by jaison2000b** [comment]
image
B4

**Comment by jaison2000b** [comment]
After 
image

**Comment by jaison2000b** [comment]
@natehavoc Thoughts?

**Comment by natehavoc** [comment]
Looks good.

Maybe add the time for the UC show?

We have our SJ dates and they will hopefully post them soon so we can get
the link.

**Comment by jaison2000b** [comment]
felt like I was missing something, i'll the time to the right of 2023 and merge

**Pull request merged**
